spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cloud_frame?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: turbo
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.emis.vi: debug
    com.emis.vi.demo.service.FeignAdminService: debug