server:
  port: 8301
spring:
  application:
    name: vi-config
  profiles:
    active: native #使用本地配置，要使用git存储改为git即可
  cloud:
    config: #配置存储配置信息
      server: #Config服务端(分布式配置中心)，从配置仓库获取配置信息并提供给客户端使用
        native: #本地仓库存储
          search-locations: classpath:/config/{application}
        git: #Git仓库存储
          uri: https://gitee.com/francis-xie/vi-config.git
          username: francis-x
          password: f123456
          clone-on-start: true #开启启动时直接从git获取配置
          search-paths: '{application}' #从对应应用名称的子目录中搜索配置
