server:
  port: 8001 #指定运行端口
spring:
  application:
    name: vi-registry #指定服务名称
eureka:
  instance:
    hostname: localhost #指定主机地址
  client:
    #Erueka是为注册中心，不需要检索服务信息;(表示是否从Eureka Server获取注册信息，默认为true。
    #如果这是一个单点的 Eureka Server，不需要同步其他节点的数据，可以设为false)
    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
    #Eureka是为注册中心,是否需要将自己注册到注册中心上(默认为true),本次位单机部署,不需要设置为true;
    #但是注册中心集群时候必须为true;因为集群时，其他Eureka需要从此Eureka中的节点上获取数据；
    register-with-eureka: false #指定是否要注册到注册中心（注册中心不需要开启）
  server:
    enable-self-preservation: false #关闭保护模式
