server:
  port: 8003
spring:
  application:
    name: vi-registry
eureka:
  instance:
    #hostname: replica2
    hostname: localhost
  client:
    serviceUrl:
      #defaultZone: http://replica1:8002/eureka/ #注册到另一个Eureka注册中心
      defaultZone: http://localhost:8002/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true