spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cloud_frame?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: turbo
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cloud-port
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /vi
    username: vi
    password: vi
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
# 日志配置
logging:
  level:
    org.springframework.data.mongodb.core: debug
    com.emis.vi.mapper: debug
    com.emis.vi.portal.dao: debug